[tool.poetry]
name = "gramep"
version = "0.1.0"
description = "GRAMEP - Genome vaRiation Analysis from the Maximum Entropy Principle"
authors = [
    "Matheus Pimenta <matheus.pimenta@outlook.com>",
    "Fabricio Lopes <fabricio@utfpr.edu.br>",
    ]
maintainers = [
    "Matheus Pimenta <matheus.pimenta@outlook.com>",
]
readme = "README.md"
license = "MIT"
packages = [{include = "gramep"}]
classifiers = [
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Natural Language :: English",
    "Environment :: Console",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.urls]
"Code" = "https://github.com/omatheuspimenta/GRAMEP"
"Bug Tracker" = "https://github.com/omatheuspimenta/GRAMEP/issues"
"Documentation" = "https://gramep.readthedocs.io/en/latest/"

[tool.poetry.scripts]
gramep = "gramep.cli:app"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.2"
rich = "^13.5.2"
biopython = "^1.81"
gffpandas = "^1.2.0"
pandas = "^2.0.3"
joblib-progress = "^1.0.3"
regex = "^2023.8.8"
pathlib = "^1.0.1"
levenshtein = "^0.21.1"
matplotlib = "^3.7.2"
scikit-learn = "^1.3.0"
seaborn = "^0.13.0"
typer = "^0.9.0"
joblib = "^1.3.2"
thefuzz = "^0.20.0"
polars = "^0.19.13"
toytree = "^2.0.1"
upsetplot = "^0.8.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
blue = "^0.9.1"
isort = "^5.12.0"
taskipy = "^1.11.0"
ruff = "^0.0.289"
mypy = "^1.5.1"


[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.1.17"
mkdocstrings = "^0.22.0"
mkdocstrings-python = "^1.1.2"
mkdocs-macros-plugin = "^1.0.4"
jinja2 = "^3.1.2"
termynal = "^0.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
codeck = "blue --check --diff . && isort --check --diff ."
codecg = "blue . && isort ."
docs = "mkdocs serve"
lintck = "ruff check ."
lintcg = "ruff check --fix ."
pre_test = "task codeck"
test = "pytest -s -x --cov=gramep -vv"
post_test = "coverage html"

[tool.mypy]
ignore_missing_imports = true
plugins = "numpy.typing.mypy_plugin"
